apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testrbac-rb
  namespace: developer
subjects:
  - kind: ServiceAccount
    name: dev
    namespace: developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: testrbac-role