apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
  #   app: nginx
  # annotations:
  #   branch: staging
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
